# fiber configuration
# Defaults are shown, commented out
# Some values have no defaults and must be filled in
[node]
genesis_signature_str = "b3e3f118307ab7729b5480634cad554a1888c9944125ca676b63102ca250f5e440113c11360f3c8bf5d4f3ff167738e33814a15c7c6a765fb851de1565b8bd0001"
genesis_address_str = "pZ9RPocV6CGoQYbwe36wyChSVtKmXfoQW2"
blockchain_pubkey_str = "022c67fe688692a73f98386bca1cf1d75e72212692397ae0f3425c46ac66773784"
blockchain_seckey_str = "83dc765c9f0dc5187176293de3c4fd0cb269b6a2fcece9978d989cbf44c107a7"
genesis_timestamp = 1426562704
genesis_coin_volume = 100e10
default_connections = []
peer_list_url = "https://127.0.0.1/peers.txt"
# port = 6000
# web_interface_port = 6420
# unconfirmed_burn_factor = 10
# unconfirmed_max_transaction_size = 32 * 1024
# unconfirmed_max_decimals = 3
# create_block_burn_factor = 10
# create_block_max_transaction_size = 32 * 1024
# create_block_max_decimals = 3
# max_block_transactions_size = 32 * 1024
display_name = "TweetCoin"
ticker = "TWT"
# coin_hours_display_name = "Coin Hours"
# coin_hours_display_name_singular = "Coin Hour"
coin_hours_ticker = "TCH"
# explorer_url = "https://explorer.skycoin.com"
# bip44_coin = 8000

[params]
distribution_addresses = ["2Qi1uAg13jgH4pUnnTaymBBgd29d2eA1Tfd"]
                           
distribution_addresses_total = 1
initial_unlocked_count = 1
max_coin_supply = 1000000

